.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH WallpaperDownloader 1 "2017-06-20" "" "WallpaperDownloader's Manual"

.SH NAME
WallpaperDownloader \- GUI application for downloading, managing and setting wallpapers from different sources.

.SH SYNOPSIS
.B wallpaperdownloader
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the \fBWallpaperDownloader\fP program. The \fBWallpaperDownloader\fP program is for downloading, managing and setting wallpapers from different sources.
 Select the exact keywords you want to use and find automatically your favorite wallpapers searching on different providers simultaneously.
 Use the background changer process to change the default wallpaper and set your favorite wallpapers or delete those which you don't want anynmore directly from the GUI.

.SH NOTES
\fBWallpaperDownloader\fP is a graphical application, so no command line interface has been implemented.
For more information, please visit the project's site at https://bitbucket.org/eloy_garcia_pca/wallpaperdownloader

.SH BUGS
To report a bug, please visit https://bitbucket.org/eloy_garcia_pca/wallpaperdownloader/issues

.SH AUTHOR
Eloy García Almadén (eloy.garcia.pca@gmail.com)
